# The name that will appear on the GitHub repository actions page
name: CI/CD using GitHub Actions

# Event trigger - Executed when a push is made to the main or develop branch
on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Cache Gradle dependencies to improve build times
      - name: Gradle Caching
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
    


      # Create properties file for the main branch - application.properties
      - name: Create application.properties
        if: contains(github.ref, 'main')
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.properties }}" > src/main/resources/application.properties

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build with Gradle
      - name: Build with Gradle
        run: ./gradlew clean build --exclude-task test
        
      # Initialize Gradle Wrapper and fetch necessary files
      - name: Initialize Gradle Wrapper
        run: |
          chmod +x gradlew
          ./gradlew wrapper --gradle-version 7.6.1
          ./gradlew --version

      # Copy JAR file to EC2 instance
      - name: Copy JAR file to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_PASSWORD }}
          source: "build/libs/*.jar"
          target: "/home/ubuntu/app.jar"

      # SSH into EC2 instance and deploy
      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/ubuntu
            java -jar -Dspring.config.location=./application.properties -Duser.timezone=Asia/Seoul app.jar &
