# github repository actions 페이지에 나타날 이름
name: CI/CD using github actions

# event trigger
# main이나 develop 브랜치에 push가 되었을 때 실행
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:

      # JDK setting - github actions에서 사용할 JDK 설정 (프로젝트나 AWS의 java 버전과 달라도 무방)
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # gradle caching - 빌드 시간 향상
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
          
      # 환경별 properties 파일 생성(1) - application.properties
      - name: Make application.properties
        if: |
          contains(github.ref, 'main') 
        run: |
          mkdir -p ./src/main/resources # resources 폴더 생성
          touch ./src/main/resources/application.properties # application.properties 생성
          echo "${{ secrets.properties }}" > ./src/main/resources/application.properties # github actions에서 설정한 값을 application.properties 파일에 쓰기
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build with Gradle
        run: ./gradlew clean build --exclude-task test

      # EC2로 파일 복사
      - name: Generate unique filename
        id: generate_filename
        run: echo "::set-output name=filename::$(date +%s)"

      - name: Copy files to EC2 instance
        run: |
          mkdir -p /tmp/archive
          cp target/*.jar /tmp/archive/
          tar -czvf /tmp/${{ steps.generate_filename.outputs.filename }}.tar.gz -C /tmp/archive/ .

      # EC2에 파일 전송
      - name: Transfer files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: /tmp/${{ steps.generate_filename.outputs.filename }}.tar.gz
          target: /home/ubuntu/${{ steps.generate_filename.outputs.filename }}.tar.gz

      # EC2에서 압축 해제
      - name: Extract files on EC2
        run: ssh -i ${{ secrets.SERVER_SSH_KEY }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'tar -xzvf /home/ubuntu/${{ steps.generate_filename.outputs.filename }}.tar.gz -C /home/ubuntu/'

      # EC2에서 애플리케이션 실행
      - name: Start application on EC2 instance
        run: ssh -i ${{ secrets.SERVER_SSH_KEY }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'nohup java -jar /home/ubuntu/app.jar > /dev/null 2>&1 &'
