# The name that will appear on the github repository actions page
name: CI/CD using github actions

# event trigger
# Executed when a push is made to the main or develop branch
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:

      # JDK setting - JDK settings to be used in github actions (It doesn't matter if it is different from the project or AWS java version)
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # gradle caching - improve build times
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      # Create properties file for each environment (1) - application.properties
      - name: make application.properties
        if: |
          contains(github.ref, 'main')
        run: |
          mkdir ./src/main/resources # create resources folder
          cd ./src/main/resources # go to resources folder
          touch ./application.properties # create application.properties
          echo "${{ secrets.properties }}" > ./application.properties # Write values ​​set in github actions to application.properties file
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6.1
          arguments: build
          run: ./gradlew clean build --exclude-task test
          
      - name: SCP Jar
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: "./app.jar"
          target: "/app
