name: Push to Branch

on:
  push:
    branches:
      - main # Replace with your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to branch
        run: |
          git config --local user.email "minina0407@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Push to branch"
          git push origin main # Replace with your desired branch
